sonar.projectKey=fried-day_fried-ui
sonar.organization=fried-day
sonar.sources=packages/react/src,packages/styles/src
sonar.tests=packages/react/src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/.turbo/**,**/coverage/**,**/.source/**
sonar.javascript.lcov.reportPaths=packages/react/coverage/lcov.info,apps/storybook/coverage/lcov.info
sonar.coverage.exclusions=**/*.stories.tsx
sonar.cpd.exclusions=**/*.css,**/*.stories.tsx,**/*.test.ts,**/*.test.tsx
sonar.qualitygate.ignoreSmallChanges=false
