name: Chromatic

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: chromatic-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: pnpm build:storybook
      - uses: chromaui/action@a01e849cbc1f51ec5743358b4d7f9a1eadadf44e
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/storybook
          storybookBuildDir: dist
          exitOnceUploaded: true
          autoAcceptChanges: main
