name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_call:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: pnpm audit:deps

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: pnpm lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: pnpm typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: Install Playwright Chromium
        run: pnpm --filter=storybook playwright:install
      - run: pnpm test

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: pnpm format

  sonar:
    name: Sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: pnpm --filter @fried-ui/react test:coverage
      - uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  size:
    name: Bundle Size
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - uses: preactjs/compressed-size-action@8518045ed95e94e971b83333085e1cb99aa18aa8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-script: build:react
          pattern: "packages/react/dist/**/*.mjs"
          exclude: "**/*.d.ts"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [audit, lint, typecheck, test, format]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: pnpm build

  preview-release:
    name: Preview Release
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: pnpm build
      - run: pnpm release:preview
