name: CI

on:
  pull_request:
    branches: [main]
  workflow_call:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: ./.github/actions/setup
      - run: pnpm audit:deps

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: ./.github/actions/setup
      - run: pnpm lint

  sort:
    name: Sort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: ./.github/actions/setup
      - run: pnpm sort

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: ./.github/actions/setup
      - run: pnpm typecheck

  sonar:
    name: Sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Install Playwright Chromium
        run: pnpm --filter=storybook playwright:install
      - run: pnpm test:coverage
      - uses: SonarSource/sonarqube-scan-action@59db25f34e16620e48ab4bb9e4a5dce155cb5432
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  size:
    name: Bundle Size
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: ./.github/actions/setup
      - uses: preactjs/compressed-size-action@66325aad6443cb7cf89c4bfcd414aea2367cda94
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-script: build:react
          pattern: "packages/react/dist/**/*.mjs"
          exclude: "**/*.d.ts"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [audit, lint, sort, typecheck, sonar]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: ./.github/actions/setup
      - run: pnpm build

  preview-release:
    name: Preview Release
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: pnpm build
      - run: pnpm release:preview
