name: Size

on:
  pull_request:
    branches: [main]
    paths:
      - "packages/react/src/**"
      - "packages/styles/src/**"

permissions:
  pull-requests: write

jobs:
  size:
    name: Bundle Size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - uses: preactjs/compressed-size-action@8518045ed95e94e971b83333085e1cb99aa18aa8 # v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-script: build:react
          pattern: "packages/react/dist/**/*.mjs"
          exclude: "**/*.d.ts"
